version: '3.8'
services:      
  swim-assembler: 
    container_name: swim-assembler
    image: lagarnicachavira/swim-assembler-public:latest
    restart: always
    environment:
      # app environment
      BOILERPLATE_ENV: 'prod'
      # default database connection URLS for sqlalchemy
      USER_DATABASE_URL: 'mysql://user:password@localhost:3306/userdb' 
      # model database url
      MODEL_DATABASE_URL: 'mongodb://user:password@localhost:27017/modeldb?authSource=admin'
      # workflow database url
      WORKFLOW_DATABASE_URL: 'mongodb://user:password@localhost:27017/workflowdb?authSource=admin'
      # secret key
      SECRET_KEY: 'yoursecretapikeyhere'
    ports:
      # <host port> : <application port>
      - '5020:5002'
